packages:
  - 'frontend'
  - 'backend'
  - 'config'
  - 'tools'
  - 'shared/*'
  - 'ai-systems/*'
  - 'DASHBOARD/*'
  - 'KRINS-HUB/*'
  - 'AI_INTEGRATION/*'
  - 'DECISION_MANAGEMENT'
  - 'GOVERNANCE_PROCESS'
  - 'KNOWLEDGE_ORGANIZATION'
  - 'ORGANIZATIONAL_INTELLIGENCE'
  - 'TEAM_COLLABORATION'